name: app-ci-pipeline
env: 
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
on:
    push:
        branches:
            - master
        paths:
            - 'src/**'
            - 'Dockerfile'
            - '.github/workflows/**'
            - '.deploy/**'
    pull_request:
        branches:
            - master
jobs:
    test: 
        name: Run api Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - name: Install all dependencies
              run: npm install
            - name: Run tests
              run: npm test
            
