name: app-ci-pipeline
env: 
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - 'Dockerfile'
            - '.github/workflows/**'
            - '.deploy/**'
    pull_request:
        branches:
            - main
jobs:
    test: 
        name: Run api Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - name: Install all dependencies
              run: npm install
            - name: Run tests
              run: npm test
    build-and-push-docker-image:
        name: Build and push Docker image to ECR
        runs-on: ubuntu-latest
        needs: test
        environment: nomad-stage
        if: github.ref == 'refs/heads/main'
        steps:
            - uses: actions/checkout@v2
            - run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
            - run: docker build -t johnny711dock/terra-project-api .
            - run: docker push johnny711dock/terra-project-api
            
